#!/bin/bash
MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"
# Initialize constants here
export REGEX='^(FMLR#[0-9]+ : .{1,200})$'
export ERROR_MSG="El formato del Commit Message debe cumplir con REGEX: \"${REGEX}\""
if [[ $FILE_CONTENT =~ $REGEX ]]; then
 echo "Good commit!"
else
  echo "Bad commit \"$FILE_CONTENT\""
 echo $ERROR_MSG
 exit 1
fi
exit 0